defaults:
  - train
  - _self_

postfix: eval_ckpt
dont_save: False
n_eval_episodes: 50
ckpt_dir: ./exp_local/${task}/${agent.name}/d${num_demo}/s${seed}/model
ckpt_episode: latest

use_wb: True
project_name: dex
entity_name: thuang22

# MPI
mpi: {rank: null, is_chef: null, num_workers: null}

# Working space
hydra:
  run:
    dir: ./exp_local/${task}/${agent.name}/d${num_demo}/eval/s${seed}
