defaults:
  - agent: VisDEX
  - _self_

# File path
cwd: ${hydra:runtime.output_dir}

# Training params
des: close_divide_loss

n_train_steps: 100_001 # 100001
n_eval: 500 #10
n_save: 10 #5
n_log: 100
num_demo: 100 #100
n_seed_steps: ${agent.n_seed_steps}

replay_buffer_capacity: 1000 #100_000
batch_size: 128
device: cuda:0
seed: 21
task: NeedlePick-v0
postfix: null
dont_save: False
n_eval_episodes: 20
demo_path: /home/student/code/SAM-rbt-sim2real/surrol/data/demo/data_PegTransfer-v0_random_100.npz
#demo_path: ./surrol/data/demo/data_PickandPlace-v0_random_100_far.npz

#demo_path: ./surrol/data/demo/data_PegTransfer-v0_random_100.npz
#demo_path: /home/student/code/SAM-rbt-sim2real/surrol/data/demo/data_NeedlePick-v0_random_100_96.npz
use_wb: True
project_name: visdex
entity_name: picksh

use_visual: True

# Resume training
resume_training: False
ckpt_dir: /home/student/code/SAM-rbt-sim2real/exp_local/NeedlePick-v0/VisDEX/d100/s56
ckpt_episode: latest
# MPI
mpi: {rank: null, is_chef: null, num_workers: null}

# Working space
hydra:
  run:
    dir: ./exp_local/${task}/${agent.name}/d${num_demo}/s${seed}
  sweep:
    dir: ./exp_local/${task}/${agent.name}/d${num_demo}
    subdir: ${seed}
  sweeper:
    params:
      seed: 1,2,3,4,5
