_target_: diffusion_policy.workspace.train_robomimic_image_workspace.TrainRobomimicImageWorkspace
checkpoint:
  save_last_ckpt: true
  save_last_snapshot: false
  topk:
    format_str: epoch={epoch:04d}-test_mean_score={test_mean_score:.3f}.ckpt
    k: 5
    mode: max
    monitor_key: test_mean_score
dataloader:
  batch_size: 64
  num_workers: 16
  persistent_workers: false
  pin_memory: true
  shuffle: true
dataset_obs_steps: 10
exp_name: default
horizon: 4
keypoint_visible_rate: 1.0
logging:
  group: null
  id: null
  mode: online
  name: 2023.01.16-20.18.49_train_robomimic_image_pusht_image
  project: diffusion_policy_debug
  resume: true
  tags:
  - train_robomimic_image
  - pusht_image
  - default
multi_run:
  run_dir: data/outputs/2023.01.16/20.18.49_train_robomimic_image_pusht_image
  wandb_name_base: 2023.01.16-20.18.49_train_robomimic_image_pusht_image
n_action_steps: 1
n_latency_steps: 0
n_obs_steps: 1
name: train_robomimic_image
past_action_visible: false
policy:
  _target_: diffusion_policy.policy.robomimic_image_policy.RobomimicImagePolicy
  algo_name: bc_rnn
  crop_shape:
  - 84
  - 84
  dataset_type: ph
  obs_type: image
  shape_meta:
    action:
      shape:
      - 5
    obs:
      agent_pos:
        shape:
        - 10
        type: low_dim
      image:
        shape:
        - 3
        - 224
        - 224
        type: rgb
  task_name: lift
shape_meta:
  action:
    shape:
    - 5
  obs:
    agent_pos:
      shape:
      - 10
      type: low_dim
    image:
      shape:
      - 3
      - 224
      - 224
      type: rgb
task:
  dataset:
    _target_: diffusion_policy.surrol_dataset.surrol_image_dataset.SurrolImageDataset
    data_root: /research/d1/gds/jwfu/SurRoL_science_robotics_experiment/experiment_data/needlepick_aloha
    T_o: 4
    T_a: 4
  env_runner:
    _target_: diffusion_policy.env_runner.surrol_image_runner.SurrolImageRunner
  image_shape:
  - 3
  - 224
  - 224
  name: pusht_image
  shape_meta:
    action:
      shape:
      - 5
    obs:
      agent_pos:
        shape:
        - 10
        type: low_dim
      image:
        shape:
        - 3
        - 224
        - 224
        type: rgb
task_name: pusht_image
training:
  checkpoint_every: 50
  debug: false
  device: cuda:0
  max_train_steps: null
  max_val_steps: null
  num_epochs: 3050
  resume: true
  rollout_every: 50
  sample_every: 5
  seed: 42
  tqdm_interval_sec: 1.0
  val_every: 1
val_dataloader:
  batch_size: 64
  num_workers: 16
  persistent_workers: false
  pin_memory: true
  shuffle: false