_target_: diffusion_policy.workspace.train_diffusion_unet_lowdim_workspace.TrainDiffusionUnetLowdimWorkspace
action_dim: 5
checkpoint:
  save_last_ckpt: true
  save_last_snapshot: false
  topk:
    format_str: epoch={epoch:04d}-test_mean_score={test_mean_score:.3f}.ckpt
    k: 5
    mode: max
    monitor_key: test_mean_score
dataloader:
  batch_size: 256
  num_workers: 1
  persistent_workers: false
  pin_memory: true
  shuffle: true
ema:
  _target_: diffusion_policy.model.diffusion.ema_model.EMAModel
  inv_gamma: 1.0
  max_value: 0.9999
  min_value: 0.0
  power: 0.75
  update_after_step: 0
exp_name: default
horizon: 4
keypoint_dim: 2
keypoint_visible_rate: 1.0
logging:
  group: null
  id: null
  mode: online
  name: 2023.01.16-20.10.02_train_diffusion_unet_lowdim_pusht_lowdim
  project: diffusion_policy_debug
  resume: true
  tags:
  - train_diffusion_unet_lowdim
  - pusht_lowdim
  - default
multi_run:
  run_dir: data/outputs/2023.01.16/20.10.02_train_diffusion_unet_lowdim_pusht_lowdim
  wandb_name_base: 2023.01.16-20.10.02_train_diffusion_unet_lowdim_pusht_lowdim
n_action_steps: 8
n_latency_steps: 0
n_obs_steps: 2
name: train_diffusion_unet_lowdim
obs_as_global_cond: false
obs_as_local_cond: false
obs_dim: 22
optimizer:
  _target_: torch.optim.AdamW
  betas:
  - 0.95
  - 0.999
  eps: 1.0e-08
  lr: 0.0001
  weight_decay: 1.0e-06
past_action_visible: false
policy:
  _target_: diffusion_policy.policy.diffusion_unet_lowdim_policy.DiffusionUnetLowdimPolicy
  action_dim: 5
  horizon: 4
  model:
    _target_: diffusion_policy.model.diffusion.conditional_unet1d.ConditionalUnet1D
    cond_predict_scale: true
    diffusion_step_embed_dim: 256
    down_dims:
    - 256
    - 512
    - 1024
    global_cond_dim: null
    input_dim: 27
    kernel_size: 5
    local_cond_dim: null
    n_groups: 8
  n_action_steps: 8
  n_obs_steps: 2
  noise_scheduler:
    _target_: diffusers.schedulers.scheduling_ddpm.DDPMScheduler
    beta_end: 0.02
    beta_schedule: squaredcos_cap_v2
    beta_start: 0.0001
    clip_sample: true
    num_train_timesteps: 100
    prediction_type: epsilon
    variance_type: fixed_small
  num_inference_steps: 100
  oa_step_convention: true
  obs_as_global_cond: false
  obs_as_local_cond: false
  obs_dim: 22
  pred_action_steps_only: false
pred_action_steps_only: false
task:
  action_dim: 5
  dataset:
    _target_: diffusion_policy.surrol_dataset_2.surrol_state_dataset.SurrolStateDataset
    data_root: /research/d1/gds/jwfu/SurRoL_science_robotics_experiment_state_based/experiment_data/pegtransfer
    T_o: 4
    T_a: 4

  env_runner:
    _target_: diffusion_policy.surrol_env_runner.surrol_state_runner.SurrolStateRunner
    env_name: PegTransferRL-v0
  keypoint_dim: 2
  name: surrol_pegtransfer_diffusion_lowdim
  obs_dim: 22
task_name: surrol_pegtransfer_diffusion_lowdim
training:
  checkpoint_every: 50
  debug: false
  device: cuda:0
  gradient_accumulate_every: 1
  lr_scheduler: cosine
  lr_warmup_steps: 500
  max_train_steps: null
  max_val_steps: null
  num_epochs: 5000
  resume: true
  rollout_every: 50
  sample_every: 5
  seed: 42
  tqdm_interval_sec: 1.0
  use_ema: true
  val_every: 1
val_dataloader:
  batch_size: 256
  num_workers: 1
  persistent_workers: false
  pin_memory: true
  shuffle: false