defaults:
  - agent: ddpg
  - _self_

# File path
cwd: ${hydra:runtime.output_dir}
des: gauze_fix_eval_render_actionsize4_demo_actionsize4_demo0_0.5_noise_[0.03-0.15]
# Training params
n_train_steps: 10000_001
n_eval: 1000
n_save: 500
n_log: 10000
num_demo: 0
n_seed_steps: ${agent.n_seed_steps}

replay_buffer_capacity: 100_000
batch_size: 128
device: cuda:0
seed: 103
task: NeedlePick-v0
postfix: null
dont_save: False
n_eval_episodes: 30
#demo_path: /research/d1/rshr/arlin/SAM-rbt-sim2real/surrol/data/demo/data_GauzeRetrieve_random_200scling1_d_matrix.npz
demo_path: /research/d1/rshr/arlin/SAM-rbt-sim2real/surrol/data/demo/data_GauzeRetrieve-v0-Traj_random_200scling1_d_matrix_traj_agtip.npz

use_wb: True
project_name: gauze_policy_1210
entity_name: yhlong

use_visual: True

# Resume training
resume_training: False
reload_vis: False
restart_vis: False
ckpt_dir: ''
vis_ckpt_dir: ''
ckpt_episode: best
buffer_dir: None
test: False

# MPI
mpi: {rank: null, is_chef: null, num_workers: null}

# Working space
hydra:
  run:
    dir: ./exp_local/${task}/${agent.name}/d${num_demo}/s${seed}
  sweep:
    dir: ./exp_local/${task}/${agent.name}/d${num_demo}
    subdir: ${seed}
  sweeper:
    params:
      seed: 1,2,3,4,5